name: Build Pierre Cybersecurity Bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022  # Windows Server 2022 with .NET 4.7.2

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore PierreCyberSecurityChatbotGUI.sln

    - name: Build Release
      run: msbuild PierreCyberSecurityChatbotGUI.sln /p:Configuration=Release /p:Platform="AnyCPU"

    - name: Create Release ZIP
      run: |
        mkdir -p artifacts
        Compress-Archive -Path "bin\Release\*" -DestinationPath "artifacts/PierreBot-Release.zip"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # Critical fix - updated from v3
      with:
        name: PierreBot-Release
        path: artifacts/PierreBot-Release.zip
